import sys

def solve():
    filename = 'input.txt'
    if len(sys.argv) > 1:
        filename = sys.argv[1]

    try:
        with open(filename, 'r') as f:
            lines = [line.strip() for line in f.readlines()]
    except FileNotFoundError:
        print(f"Please create '{filename}' with your puzzle input.")
        return

    # The program halts when register 4 equals register 0 at the eqrr instruction.
    # For this specific instruction sequence, the values of r4 compared to r0 are
    # generated by a tight loop. We can simulate that directly.

    # Extract the constant loaded into r4 (line: seti <const> 5 4)
    const = None
    for line in lines:
        if line.startswith('seti') and line.endswith(' 5 4'):
            parts = line.split()
            const = int(parts[1])
            break
    if const is None:
        const = 0

    seen = set()
    last_unique = None
    first = None

    r4 = 0
    while True:
        r3 = r4 | 65536
        r4 = const

        while True:
            r2 = r3 & 255
            r4 = r4 + r2
            r4 &= 16777215
            r4 *= 65899
            r4 &= 16777215
            if r3 < 256:
                break
            r3 //= 256

        if first is None:
            first = r4

        if r4 in seen:
            break
        seen.add(r4)
        last_unique = r4

    print(first)
    print(last_unique)

if __name__ == '__main__':
    solve()
